// Package subscribe implements the publish/subscribe half of the "ledger"
// JSON-RPC namespace: push notifications about momentums and account
// blocks as they are committed to the chain.
//
// Subscriptions are only available on connection-oriented transports.
// Websocket and ipc connections are served by the rpc/server package
// with subscription support enabled, while plain HTTP requests are
// handled in single-request mode with subscriptions disabled, so a
// subscribe call over HTTP fails with ErrNotificationsUnsupported from
// the rpc/server package.
//
// A client subscribes by calling the ledger.subscribe method with the
// subscription name as first positional parameter, followed by the
// arguments of that subscription, if any. The names are the lower-camel
// forms of the exported methods of Api: momentums, allAccountBlocks,
// accountBlocksByAddress and unreceivedAccountBlocksByAddress. The call
// returns a subscription id; from then on every event is pushed to the
// client as a JSON-RPC notification with method ledger.subscription
// whose params object carries the subscription id and the event payload.
// Calling ledger.unsubscribe with the id cancels the subscription, as
// does closing the connection.
//
// Internally a process-wide Server registers with the chain as a
// momentum event listener and a single worker goroutine fans each
// inserted momentum out to the installed subscriptions. The hand-off
// from chain insertion to the worker uses bounded buffers, and events
// are dropped (with an error log) when a buffer is full, so delivery is
// best-effort under sustained load. Only events committed after a
// subscription is installed are streamed; there is no backfill.
package subscribe

import (
	"context"
	"sync"

	"github.com/inconshreveable/log15"

	"github.com/zenon-network/go-zenon/chain"
	"github.com/zenon-network/go-zenon/chain/nom"
	"github.com/zenon-network/go-zenon/common"
	"github.com/zenon-network/go-zenon/common/types"
	rpc "github.com/zenon-network/go-zenon/rpc/server"
)

// Buffer sizes of the Server's internal channels. The momentum and
// account-block channels drop events when full (see
// Server.InsertMomentum); the install channel makes a subscribe call
// block once installSize installations are pending.
const (
	acChanSize    = 100
	mChanSize     = 100
	installSize   = 100
	uninstallSize = 100
)

var (
	oneSingleton sync.Mutex
	singleton    *Server
)

// Momentum is the notification payload of the momentums subscription:
// the hash and height of a momentum that was just inserted into the
// chain. Each notification carries a one-element array of these
// objects.
type Momentum struct {
	Hash   types.Hash `json:"hash"`
	Height uint64     `json:"height"`
}

// AccountBlock is the notification payload of the account-block
// subscriptions: a trimmed-down view of a block committed by a
// momentum. ToAddress is the destination of a send block; FromHash is
// the hash of the send block a receive block accepts (zero otherwise).
// Each notification carries an array of these objects covering one
// momentum, with descendant blocks generated by embedded contracts
// flattened into the same array right after their parent.
type AccountBlock struct {
	BlockType uint64        `json:"blockType"`
	Hash      types.Hash    `json:"hash"`
	Height    uint64        `json:"height"`
	Address   types.Address `json:"address"`
	ToAddress types.Address `json:"toAddress"`
	FromHash  types.Hash    `json:"fromHash"`
}

func newAccountBlock(block *nom.AccountBlock) []*AccountBlock {
	all := make([]*AccountBlock, 1, len(block.DescendantBlocks)+1)
	all[0] = &AccountBlock{
		BlockType: block.BlockType,
		Hash:      block.Hash,
		Height:    block.Height,
		Address:   block.Address,
		ToAddress: block.ToAddress,
		FromHash:  block.FromBlockHash,
	}
	for _, dBlock := range block.DescendantBlocks {
		all = append(all, newAccountBlock(dBlock)...)
	}
	return all
}

// Api implements the subscription handlers of the "ledger" JSON-RPC
// namespace. Because each exported method takes a context and returns a
// subscription, the RPC server registers it as a subscription callback
// instead of a regular method: it is invoked through ledger.subscribe
// with the method's lower-camel name as first parameter and streams its
// events as ledger.subscription notifications. New subscriptions are
// handed to the shared Server, which owns the event fan-out.
type Api struct {
	chain     chain.Chain
	log       log15.Logger
	installCh chan *Subscription // add subscription
}

// Server is the singleton behind Api that connects the chain to the
// active subscriptions. It registers with the chain as a momentum event
// listener, converts each inserted momentum into Momentum and
// AccountBlock events on buffered channels, and fans them out to the
// installed subscriptions from a single worker goroutine. Its Init,
// Start and Stop methods tie it into the node lifecycle.
type Server struct {
	*Api

	started       bool
	uninstallCh   chan *Subscription // remove subscription
	acCh          chan []*AccountBlock
	mCh           chan *Momentum
	stopped       chan struct{}
	subscriptions map[SubscriptionType]map[rpc.ID]*Subscription

	wg sync.WaitGroup
}

// GetSubscribeServer returns the process-wide subscription Server,
// creating it bound to the given chain on first call. Later calls
// return the same instance regardless of the argument until Stop clears
// the singleton.
func GetSubscribeServer(chain chain.Chain) *Server {
	oneSingleton.Lock()
	defer oneSingleton.Unlock()

	if singleton == nil {
		singleton = &Server{
			Api: &Api{
				chain:     chain,
				log:       common.RPCLogger.New("module", "subscribe_api"),
				installCh: make(chan *Subscription, installSize),
			},

			acCh:          make(chan []*AccountBlock, acChanSize),
			mCh:           make(chan *Momentum, mChanSize),
			uninstallCh:   make(chan *Subscription, uninstallSize),
			stopped:       make(chan struct{}),
			subscriptions: make(map[SubscriptionType]map[rpc.ID]*Subscription),
		}
	}
	return singleton
}

// GetSubscribeApi returns the Api of the singleton Server so the RPC
// layer can register it under the "ledger" namespace. It panics if
// GetSubscribeServer has not been called or the server has not been
// started yet, making wrong startup order fail fast.
func GetSubscribeApi() *Api {
	oneSingleton.Lock()
	defer oneSingleton.Unlock()
	if singleton == nil {
		panic("must call GetSubscribeServer once before calling GetSubscribeApi")
	}
	if !singleton.started {
		panic("must start SubscribeServer before calling GetSubscribeApi")
	}
	return singleton.Api
}

// Init allocates one subscription table per subscription type. It must
// run before Start and always returns nil.
func (s *Server) Init() error {
	s.log.Info("init")
	defer s.log.Info("finish init")
	for i := FirstSubscriptionType; i < LastSubscriptionType; i++ {
		s.subscriptions[i] = make(map[rpc.ID]*Subscription)
	}
	return nil
}

// Start registers the server as a momentum event listener on the chain
// and launches the worker goroutine that serves installations and
// broadcasts. It always returns nil.
func (s *Server) Start() error {
	s.log.Info("start")
	defer s.log.Info("finish start")
	s.started = true
	s.chain.Register(s)
	s.wg.Add(1)
	go func() {
		s.work()
		s.wg.Done()
	}()
	return nil
}

// Stop unregisters from the chain, signals the worker goroutine to exit
// and waits for it, and clears the package singleton so a new server
// can be created. Active subscriptions are not notified; the worker
// simply drops its tables on exit. It always returns nil.
func (s *Server) Stop() error {
	s.log.Info("stop")
	defer s.log.Info("finish stop")
	s.started = false
	s.chain.UnRegister(s)
	close(s.stopped)
	singleton = nil
	s.log.Debug("wg.Wait() api Server.Stop()")
	s.wg.Wait()
	s.log.Debug("wg.Wait() api Server.Stop() finish")
	return nil
}

// InsertMomentum implements the chain's momentum event listener
// interface. It converts the inserted momentum into a Momentum event
// and a flattened slice of AccountBlock events (descendant blocks
// included) and queues them for the worker goroutine. The queues are
// non-blocking: when one is full the event is dropped and an error is
// logged, so subscribers can miss events under sustained load.
func (s *Server) InsertMomentum(detailed *nom.DetailedMomentum) {
	select {
	case s.mCh <- &Momentum{
		Hash:   detailed.Momentum.Hash,
		Height: detailed.Momentum.Height,
	}:
	default:
		s.log.Error("can't insert momentum for broadcast", "reason", "channel is full", "momentum-identifier", detailed.Momentum.Identifier())
	}

	abEvents := make([]*AccountBlock, 0, len(detailed.AccountBlocks))
	for _, block := range detailed.AccountBlocks {
		abEvents = append(abEvents, newAccountBlock(block)...)
	}
	select {
	case s.acCh <- abEvents:
	default:
		s.log.Error("can't insert account-blocks for broadcast", "reason", "channel is full", "momentum-identifier", detailed.Momentum.Identifier())
	}
	return
}

// DeleteMomentum implements the chain's momentum event listener
// interface as a no-op: rollbacks are not broadcast to subscribers.
func (s *Server) DeleteMomentum(*nom.DetailedMomentum) {
}

func (s *Server) work() {
	log := s.log.New("module", "worker")
	defer common.RecoverStack()
	log.Info("start event loop")
	defer log.Info("stop event loop")
	for {
		select {
		case <-s.stopped:
			log.Info("stopped")
			s.subscriptions = nil
			return
		case sub := <-s.installCh:
			s.install(sub)
		case sub := <-s.uninstallCh:
			s.uninstall(sub)
		case momentums := <-s.mCh:
			s.broadcastMomentums(momentums)
		case blocks := <-s.acCh:
			s.broadcastBlocks(blocks)
		}
	}
}

// BroadcastStats counts, for one broadcast pass, how many subscriptions
// were notified and how many were found closed and uninstalled. It only
// feeds the log line emitted after each pass.
type BroadcastStats struct {
	NumNotify     int
	NumUninstalls int
}

func (s *Server) install(subscription *Subscription) {
	s.log.Info("install", "id", subscription.rpc.ID)
	s.subscriptions[subscription.options.subscriptionType][subscription.rpc.ID] = subscription
}
func (s *Server) uninstall(subscription *Subscription) {
	s.log.Info("uninstall", "id", subscription.rpc.ID)
	delete(s.subscriptions[subscription.options.subscriptionType], subscription.rpc.ID)
}
func (s *Server) broadcast(subscription *Subscription, data interface{}, stats *BroadcastStats) {
	if subscription.Closed() {
		stats.NumUninstalls += 1
		s.uninstall(subscription)
	} else {
		stats.NumNotify += 1
		subscription.Notify(data)
	}
}
func (s *Server) broadcastMomentums(momentum *Momentum) {
	if momentum == nil {
		return
	}
	startTime := common.Clock.Now()
	stats := &BroadcastStats{}

	for _, f := range s.subscriptions[MomentumsSubscription] {
		s.broadcast(f, []interface{}{momentum}, stats)
	}

	s.log.Info("finish broadcasting momentum", "identifier", momentum, "elapsed", common.Clock.Now().Sub(startTime), "stats", stats)
}
func (s *Server) broadcastBlocks(blocks []*AccountBlock) {
	if len(blocks) == 0 {
		return
	}
	startTime := common.Clock.Now()
	stats := &BroadcastStats{}

	byAddress := make(map[types.Address][]*AccountBlock)
	unreceivedByAddress := make(map[types.Address][]*AccountBlock)
	for _, block := range blocks {
		if _, ok := byAddress[block.Address]; !ok {
			byAddress[block.Address] = make([]*AccountBlock, 0)
		}
		byAddress[block.Address] = append(byAddress[block.Address], block)
		if nom.IsSendBlock(block.BlockType) {
			if _, ok := unreceivedByAddress[block.ToAddress]; !ok {
				unreceivedByAddress[block.ToAddress] = make([]*AccountBlock, 0)
			}
			unreceivedByAddress[block.ToAddress] = append(unreceivedByAddress[block.ToAddress], block)
		}
	}

	for _, f := range s.subscriptions[AllAccountBlocksSubscription] {
		s.broadcast(f, blocks, stats)
	}
	for _, f := range s.subscriptions[AccountBlocksSubscriptionByAddress] {
		if blocks, ok := byAddress[f.options.address]; ok {
			s.broadcast(f, blocks, stats)
		}
	}
	for _, f := range s.subscriptions[UnreceivedAccountBlocksSubscriptionByAddress] {
		if blocks, ok := unreceivedByAddress[f.options.address]; ok {
			s.broadcast(f, blocks, stats)
		}
	}

	s.log.Info("finish broadcasting account-blocks", "elapsed", common.Clock.Now().Sub(startTime), "stats", stats)
}

func (s *Api) subscribe(ctx context.Context, options *subscriptionOptions) (*rpc.Subscription, error) {
	notifier, supported := rpc.NotifierFromContext(ctx)
	if !supported {
		return nil, rpc.ErrNotificationsUnsupported
	}
	subscription := NewSubscription(notifier, options)
	s.installCh <- subscription
	return subscription.rpc, nil
}

// Momentums creates a subscription that streams the hash and height of
// every momentum inserted into the chain. Each notification carries an
// array holding a single Momentum object.
//
// JSON-RPC: ledger.subscribe with first parameter "momentums". The
// reply is the subscription id; ErrNotificationsUnsupported is returned
// on transports without notification support (plain HTTP).
func (s *Api) Momentums(ctx context.Context) (*rpc.Subscription, error) {
	s.log.Info("new subscription", "type", "Momentums")
	return s.subscribe(ctx, NewMomentumsSubscription())
}

// AllAccountBlocks creates a subscription that streams every account
// block committed to the chain. Each notification carries the blocks of
// one momentum as an array of AccountBlock objects, descendant blocks
// included.
//
// JSON-RPC: ledger.subscribe with first parameter "allAccountBlocks".
// The reply is the subscription id; ErrNotificationsUnsupported is
// returned on transports without notification support (plain HTTP).
func (s *Api) AllAccountBlocks(ctx context.Context) (*rpc.Subscription, error) {
	s.log.Info("new subscription", "type", "AllAccountBlocks")
	return s.subscribe(ctx, NewBlocksSubscription())
}

// AccountBlocksByAddress creates a subscription that streams the
// committed account blocks of a single account chain, i.e. blocks whose
// address field equals the given address. Each notification carries the
// matching blocks of one momentum as an array of AccountBlock objects;
// momentums without matching blocks produce no notification.
//
// JSON-RPC: ledger.subscribe with parameters "accountBlocksByAddress"
// and the address. The reply is the subscription id;
// ErrNotificationsUnsupported is returned on transports without
// notification support (plain HTTP).
func (s *Api) AccountBlocksByAddress(ctx context.Context, address types.Address) (*rpc.Subscription, error) {
	s.log.Info("new subscription", "type", "AccountBlocksByAddress")
	return s.subscribe(ctx, NewBlocksByAddressSubscription(address))
}

// UnreceivedAccountBlocksByAddress creates a subscription that streams
// send blocks destined for the given address as they are committed,
// that is, transfers the address has yet to receive. Each notification
// carries the matching blocks of one momentum as an array of
// AccountBlock objects. Only sends committed after the subscription is
// installed are streamed; transfers already pending must be fetched
// with ledger.getUnreceivedBlocksByAddress.
//
// JSON-RPC: ledger.subscribe with parameters
// "unreceivedAccountBlocksByAddress" and the address. The reply is the
// subscription id; ErrNotificationsUnsupported is returned on
// transports without notification support (plain HTTP).
func (s *Api) UnreceivedAccountBlocksByAddress(ctx context.Context, address types.Address) (*rpc.Subscription, error) {
	s.log.Info("new subscription", "type", "UnreceivedAccountBlocksByAddress")
	return s.subscribe(ctx, NewToUnreceivedBlocksSubscription(address))
}
