// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.22.3
// source: consensus/storage/election_data.proto

package storage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PillarDelegationProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProducingAddress []byte `protobuf:"bytes,1,opt,name=producingAddress,proto3" json:"producingAddress,omitempty"`
	Name             string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Weight           []byte `protobuf:"bytes,3,opt,name=weight,proto3" json:"weight,omitempty"`
}

func (x *PillarDelegationProto) Reset() {
	*x = PillarDelegationProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_consensus_storage_election_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PillarDelegationProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PillarDelegationProto) ProtoMessage() {}

func (x *PillarDelegationProto) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_storage_election_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PillarDelegationProto.ProtoReflect.Descriptor instead.
func (*PillarDelegationProto) Descriptor() ([]byte, []int) {
	return file_consensus_storage_election_data_proto_rawDescGZIP(), []int{0}
}

func (x *PillarDelegationProto) GetProducingAddress() []byte {
	if x != nil {
		return x.ProducingAddress
	}
	return nil
}

func (x *PillarDelegationProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PillarDelegationProto) GetWeight() []byte {
	if x != nil {
		return x.Weight
	}
	return nil
}

type ElectionDataProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Producers   [][]byte                 `protobuf:"bytes,1,rep,name=producers,proto3" json:"producers,omitempty"`
	Delegations []*PillarDelegationProto `protobuf:"bytes,2,rep,name=delegations,proto3" json:"delegations,omitempty"`
}

func (x *ElectionDataProto) Reset() {
	*x = ElectionDataProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_consensus_storage_election_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElectionDataProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElectionDataProto) ProtoMessage() {}

func (x *ElectionDataProto) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_storage_election_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElectionDataProto.ProtoReflect.Descriptor instead.
func (*ElectionDataProto) Descriptor() ([]byte, []int) {
	return file_consensus_storage_election_data_proto_rawDescGZIP(), []int{1}
}

func (x *ElectionDataProto) GetProducers() [][]byte {
	if x != nil {
		return x.Producers
	}
	return nil
}

func (x *ElectionDataProto) GetDelegations() []*PillarDelegationProto {
	if x != nil {
		return x.Delegations
	}
	return nil
}

var File_consensus_storage_election_data_proto protoreflect.FileDescriptor

var file_consensus_storage_election_data_proto_rawDesc = []byte{
	0x0a, 0x25, 0x63, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x2f, 0x73, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x2f, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x22, 0x6f, 0x0a, 0x15, 0x50, 0x69, 0x6c, 0x6c, 0x61, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x67, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2a, 0x0a, 0x10, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x69, 0x6e, 0x67, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x10, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x69, 0x6e, 0x67, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x22, 0x73, 0x0a, 0x11, 0x45, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74,
	0x61, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x65, 0x72, 0x73, 0x12, 0x40, 0x0a, 0x0b, 0x64, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x73, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x2e, 0x50, 0x69, 0x6c, 0x6c, 0x61, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x67, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x0b, 0x64, 0x65, 0x6c, 0x65, 0x67,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x65, 0x6e, 0x6f, 0x6e, 0x2d, 0x6e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x2f, 0x67, 0x6f, 0x2d, 0x7a, 0x65, 0x6e, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6e, 0x73,
	0x65, 0x6e, 0x73, 0x75, 0x73, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_consensus_storage_election_data_proto_rawDescOnce sync.Once
	file_consensus_storage_election_data_proto_rawDescData = file_consensus_storage_election_data_proto_rawDesc
)

func file_consensus_storage_election_data_proto_rawDescGZIP() []byte {
	file_consensus_storage_election_data_proto_rawDescOnce.Do(func() {
		file_consensus_storage_election_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_consensus_storage_election_data_proto_rawDescData)
	})
	return file_consensus_storage_election_data_proto_rawDescData
}

var file_consensus_storage_election_data_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_consensus_storage_election_data_proto_goTypes = []interface{}{
	(*PillarDelegationProto)(nil), // 0: storage.PillarDelegationProto
	(*ElectionDataProto)(nil),     // 1: storage.ElectionDataProto
}
var file_consensus_storage_election_data_proto_depIdxs = []int32{
	0, // 0: storage.ElectionDataProto.delegations:type_name -> storage.PillarDelegationProto
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_consensus_storage_election_data_proto_init() }
func file_consensus_storage_election_data_proto_init() {
	if File_consensus_storage_election_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_consensus_storage_election_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PillarDelegationProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_consensus_storage_election_data_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElectionDataProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_consensus_storage_election_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_consensus_storage_election_data_proto_goTypes,
		DependencyIndexes: file_consensus_storage_election_data_proto_depIdxs,
		MessageInfos:      file_consensus_storage_election_data_proto_msgTypes,
	}.Build()
	File_consensus_storage_election_data_proto = out.File
	file_consensus_storage_election_data_proto_rawDesc = nil
	file_consensus_storage_election_data_proto_goTypes = nil
	file_consensus_storage_election_data_proto_depIdxs = nil
}
