// Code generated by protoc-gen-go. DO NOT EDIT.
// source: consensus/storage/point.proto

package storage

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProducerDetailProto struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FactualNum           uint32   `protobuf:"fixed32,2,opt,name=factualNum,proto3" json:"factualNum,omitempty"`
	ExpectedNum          uint32   `protobuf:"fixed32,3,opt,name=expectedNum,proto3" json:"expectedNum,omitempty"`
	Weight               []byte   `protobuf:"bytes,4,opt,name=weight,proto3" json:"weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProducerDetailProto) Reset()         { *m = ProducerDetailProto{} }
func (m *ProducerDetailProto) String() string { return proto.CompactTextString(m) }
func (*ProducerDetailProto) ProtoMessage()    {}
func (*ProducerDetailProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c67e21f5180c21b, []int{0}
}

func (m *ProducerDetailProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProducerDetailProto.Unmarshal(m, b)
}
func (m *ProducerDetailProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProducerDetailProto.Marshal(b, m, deterministic)
}
func (m *ProducerDetailProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProducerDetailProto.Merge(m, src)
}
func (m *ProducerDetailProto) XXX_Size() int {
	return xxx_messageInfo_ProducerDetailProto.Size(m)
}
func (m *ProducerDetailProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ProducerDetailProto.DiscardUnknown(m)
}

var xxx_messageInfo_ProducerDetailProto proto.InternalMessageInfo

func (m *ProducerDetailProto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProducerDetailProto) GetFactualNum() uint32 {
	if m != nil {
		return m.FactualNum
	}
	return 0
}

func (m *ProducerDetailProto) GetExpectedNum() uint32 {
	if m != nil {
		return m.ExpectedNum
	}
	return 0
}

func (m *ProducerDetailProto) GetWeight() []byte {
	if m != nil {
		return m.Weight
	}
	return nil
}

type ConsensusPointProto struct {
	PrevHash             []byte                 `protobuf:"bytes,1,opt,name=prevHash,proto3" json:"prevHash,omitempty"`
	EndHash              []byte                 `protobuf:"bytes,2,opt,name=endHash,proto3" json:"endHash,omitempty"`
	TotalWeight          []byte                 `protobuf:"bytes,3,opt,name=totalWeight,proto3" json:"totalWeight,omitempty"`
	Content              []*ProducerDetailProto `protobuf:"bytes,4,rep,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ConsensusPointProto) Reset()         { *m = ConsensusPointProto{} }
func (m *ConsensusPointProto) String() string { return proto.CompactTextString(m) }
func (*ConsensusPointProto) ProtoMessage()    {}
func (*ConsensusPointProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c67e21f5180c21b, []int{1}
}

func (m *ConsensusPointProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsensusPointProto.Unmarshal(m, b)
}
func (m *ConsensusPointProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsensusPointProto.Marshal(b, m, deterministic)
}
func (m *ConsensusPointProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsensusPointProto.Merge(m, src)
}
func (m *ConsensusPointProto) XXX_Size() int {
	return xxx_messageInfo_ConsensusPointProto.Size(m)
}
func (m *ConsensusPointProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsensusPointProto.DiscardUnknown(m)
}

var xxx_messageInfo_ConsensusPointProto proto.InternalMessageInfo

func (m *ConsensusPointProto) GetPrevHash() []byte {
	if m != nil {
		return m.PrevHash
	}
	return nil
}

func (m *ConsensusPointProto) GetEndHash() []byte {
	if m != nil {
		return m.EndHash
	}
	return nil
}

func (m *ConsensusPointProto) GetTotalWeight() []byte {
	if m != nil {
		return m.TotalWeight
	}
	return nil
}

func (m *ConsensusPointProto) GetContent() []*ProducerDetailProto {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterType((*ProducerDetailProto)(nil), "storage.ProducerDetailProto")
	proto.RegisterType((*ConsensusPointProto)(nil), "storage.ConsensusPointProto")
}

func init() { proto.RegisterFile("consensus/storage/point.proto", fileDescriptor_8c67e21f5180c21b) }

var fileDescriptor_8c67e21f5180c21b = []byte{
	// 242 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0xd9, 0xa6, 0x34, 0x3a, 0xed, 0x69, 0x0b, 0x12, 0x44, 0x25, 0xf4, 0x94, 0x53, 0x0a,
	0x0a, 0xbe, 0x80, 0x1e, 0x3c, 0x49, 0xd8, 0x8b, 0xe7, 0x75, 0x33, 0xb6, 0x81, 0x74, 0x37, 0xec,
	0x4e, 0xd4, 0xbb, 0xcf, 0xe2, 0x7b, 0xca, 0x4e, 0x12, 0xc9, 0xa1, 0xb7, 0xf9, 0xfe, 0xc0, 0xfc,
	0xf8, 0xe0, 0xd6, 0x38, 0x1b, 0xd0, 0x86, 0x3e, 0xec, 0x03, 0x39, 0xaf, 0x0f, 0xb8, 0xef, 0x5c,
	0x63, 0xa9, 0xec, 0xbc, 0x23, 0x27, 0xd3, 0xd1, 0xdc, 0xfd, 0x08, 0xd8, 0x56, 0xde, 0xd5, 0xbd,
	0x41, 0xff, 0x8c, 0xa4, 0x9b, 0xb6, 0xe2, 0x82, 0x84, 0xa5, 0xd5, 0x27, 0xcc, 0x44, 0x2e, 0x8a,
	0x4b, 0xc5, 0xb7, 0xbc, 0x03, 0xf8, 0xd0, 0x86, 0x7a, 0xdd, 0xbe, 0xf6, 0xa7, 0x6c, 0x91, 0x8b,
	0x22, 0x55, 0x33, 0x47, 0xe6, 0xb0, 0xc6, 0xef, 0x0e, 0x0d, 0x61, 0x1d, 0x0b, 0x09, 0x17, 0xe6,
	0x96, 0xbc, 0x82, 0xd5, 0x17, 0x36, 0x87, 0x23, 0x65, 0xcb, 0x5c, 0x14, 0x1b, 0x35, 0xaa, 0xdd,
	0xaf, 0x80, 0xed, 0xd3, 0x04, 0x5c, 0x45, 0xce, 0x81, 0xe2, 0x1a, 0x2e, 0x3a, 0x8f, 0x9f, 0x2f,
	0x3a, 0x1c, 0x99, 0x64, 0xa3, 0xfe, 0xb5, 0xcc, 0x20, 0x45, 0x5b, 0x73, 0xb4, 0xe0, 0x68, 0x92,
	0x91, 0x83, 0x1c, 0xe9, 0xf6, 0x6d, 0x78, 0x95, 0x70, 0x3a, 0xb7, 0xe4, 0x23, 0xa4, 0xc6, 0x59,
	0x42, 0x1b, 0x41, 0x92, 0x62, 0x7d, 0x7f, 0x53, 0x8e, 0x83, 0x94, 0x67, 0xc6, 0x50, 0x53, 0xf9,
	0x7d, 0xc5, 0xeb, 0x3d, 0xfc, 0x05, 0x00, 0x00, 0xff, 0xff, 0xea, 0x53, 0xf2, 0xe9, 0x5e, 0x01,
	0x00, 0x00,
}
