// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.22.3
// source: consensus/storage/point.proto

package storage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProducerDetailProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FactualNum  uint32 `protobuf:"fixed32,2,opt,name=factualNum,proto3" json:"factualNum,omitempty"`
	ExpectedNum uint32 `protobuf:"fixed32,3,opt,name=expectedNum,proto3" json:"expectedNum,omitempty"`
	Weight      []byte `protobuf:"bytes,4,opt,name=weight,proto3" json:"weight,omitempty"`
}

func (x *ProducerDetailProto) Reset() {
	*x = ProducerDetailProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_consensus_storage_point_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProducerDetailProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProducerDetailProto) ProtoMessage() {}

func (x *ProducerDetailProto) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_storage_point_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProducerDetailProto.ProtoReflect.Descriptor instead.
func (*ProducerDetailProto) Descriptor() ([]byte, []int) {
	return file_consensus_storage_point_proto_rawDescGZIP(), []int{0}
}

func (x *ProducerDetailProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProducerDetailProto) GetFactualNum() uint32 {
	if x != nil {
		return x.FactualNum
	}
	return 0
}

func (x *ProducerDetailProto) GetExpectedNum() uint32 {
	if x != nil {
		return x.ExpectedNum
	}
	return 0
}

func (x *ProducerDetailProto) GetWeight() []byte {
	if x != nil {
		return x.Weight
	}
	return nil
}

type ConsensusPointProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrevHash    []byte                 `protobuf:"bytes,1,opt,name=prevHash,proto3" json:"prevHash,omitempty"`
	EndHash     []byte                 `protobuf:"bytes,2,opt,name=endHash,proto3" json:"endHash,omitempty"`
	TotalWeight []byte                 `protobuf:"bytes,3,opt,name=totalWeight,proto3" json:"totalWeight,omitempty"`
	Content     []*ProducerDetailProto `protobuf:"bytes,4,rep,name=content,proto3" json:"content,omitempty"`
}

func (x *ConsensusPointProto) Reset() {
	*x = ConsensusPointProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_consensus_storage_point_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsensusPointProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusPointProto) ProtoMessage() {}

func (x *ConsensusPointProto) ProtoReflect() protoreflect.Message {
	mi := &file_consensus_storage_point_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsensusPointProto.ProtoReflect.Descriptor instead.
func (*ConsensusPointProto) Descriptor() ([]byte, []int) {
	return file_consensus_storage_point_proto_rawDescGZIP(), []int{1}
}

func (x *ConsensusPointProto) GetPrevHash() []byte {
	if x != nil {
		return x.PrevHash
	}
	return nil
}

func (x *ConsensusPointProto) GetEndHash() []byte {
	if x != nil {
		return x.EndHash
	}
	return nil
}

func (x *ConsensusPointProto) GetTotalWeight() []byte {
	if x != nil {
		return x.TotalWeight
	}
	return nil
}

func (x *ConsensusPointProto) GetContent() []*ProducerDetailProto {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_consensus_storage_point_proto protoreflect.FileDescriptor

var file_consensus_storage_point_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x63, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x2f, 0x73, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x2f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x22, 0x83, 0x01, 0x0a, 0x13, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x66, 0x61, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x4e,
	0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x07, 0x52, 0x0a, 0x66, 0x61, 0x63, 0x74, 0x75, 0x61,
	0x6c, 0x4e, 0x75, 0x6d, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64,
	0x4e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x07, 0x52, 0x0b, 0x65, 0x78, 0x70, 0x65, 0x63,
	0x74, 0x65, 0x64, 0x4e, 0x75, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0xa5,
	0x01, 0x0a, 0x13, 0x43, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x65, 0x76, 0x48, 0x61,
	0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x70, 0x72, 0x65, 0x76, 0x48, 0x61,
	0x73, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x48, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x48, 0x61, 0x73, 0x68, 0x12, 0x20, 0x0a, 0x0b,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x36,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x65, 0x6e, 0x6f, 0x6e, 0x2d, 0x6e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x2f, 0x67, 0x6f, 0x2d, 0x7a, 0x65, 0x6e, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6e, 0x73,
	0x65, 0x6e, 0x73, 0x75, 0x73, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_consensus_storage_point_proto_rawDescOnce sync.Once
	file_consensus_storage_point_proto_rawDescData = file_consensus_storage_point_proto_rawDesc
)

func file_consensus_storage_point_proto_rawDescGZIP() []byte {
	file_consensus_storage_point_proto_rawDescOnce.Do(func() {
		file_consensus_storage_point_proto_rawDescData = protoimpl.X.CompressGZIP(file_consensus_storage_point_proto_rawDescData)
	})
	return file_consensus_storage_point_proto_rawDescData
}

var file_consensus_storage_point_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_consensus_storage_point_proto_goTypes = []interface{}{
	(*ProducerDetailProto)(nil), // 0: storage.ProducerDetailProto
	(*ConsensusPointProto)(nil), // 1: storage.ConsensusPointProto
}
var file_consensus_storage_point_proto_depIdxs = []int32{
	0, // 0: storage.ConsensusPointProto.content:type_name -> storage.ProducerDetailProto
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_consensus_storage_point_proto_init() }
func file_consensus_storage_point_proto_init() {
	if File_consensus_storage_point_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_consensus_storage_point_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProducerDetailProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_consensus_storage_point_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsensusPointProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_consensus_storage_point_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_consensus_storage_point_proto_goTypes,
		DependencyIndexes: file_consensus_storage_point_proto_depIdxs,
		MessageInfos:      file_consensus_storage_point_proto_msgTypes,
	}.Build()
	File_consensus_storage_point_proto = out.File
	file_consensus_storage_point_proto_rawDesc = nil
	file_consensus_storage_point_proto_goTypes = nil
	file_consensus_storage_point_proto_depIdxs = nil
}
