// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.22.3
// source: common/types/protobuf.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddressProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address []byte `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *AddressProto) Reset() {
	*x = AddressProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_types_protobuf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddressProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressProto) ProtoMessage() {}

func (x *AddressProto) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_protobuf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressProto.ProtoReflect.Descriptor instead.
func (*AddressProto) Descriptor() ([]byte, []int) {
	return file_common_types_protobuf_proto_rawDescGZIP(), []int{0}
}

func (x *AddressProto) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

type HashProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *HashProto) Reset() {
	*x = HashProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_types_protobuf_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HashProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashProto) ProtoMessage() {}

func (x *HashProto) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_protobuf_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashProto.ProtoReflect.Descriptor instead.
func (*HashProto) Descriptor() ([]byte, []int) {
	return file_common_types_protobuf_proto_rawDescGZIP(), []int{1}
}

func (x *HashProto) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type HashHeightProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash   *HashProto `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Height uint64     `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *HashHeightProto) Reset() {
	*x = HashHeightProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_types_protobuf_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HashHeightProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashHeightProto) ProtoMessage() {}

func (x *HashHeightProto) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_protobuf_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashHeightProto.ProtoReflect.Descriptor instead.
func (*HashHeightProto) Descriptor() ([]byte, []int) {
	return file_common_types_protobuf_proto_rawDescGZIP(), []int{2}
}

func (x *HashHeightProto) GetHash() *HashProto {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *HashHeightProto) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type AccountHeaderProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address    *AddressProto    `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	HashHeight *HashHeightProto `protobuf:"bytes,2,opt,name=hashHeight,proto3" json:"hashHeight,omitempty"`
}

func (x *AccountHeaderProto) Reset() {
	*x = AccountHeaderProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_types_protobuf_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountHeaderProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountHeaderProto) ProtoMessage() {}

func (x *AccountHeaderProto) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_protobuf_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountHeaderProto.ProtoReflect.Descriptor instead.
func (*AccountHeaderProto) Descriptor() ([]byte, []int) {
	return file_common_types_protobuf_proto_rawDescGZIP(), []int{3}
}

func (x *AccountHeaderProto) GetAddress() *AddressProto {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *AccountHeaderProto) GetHashHeight() *HashHeightProto {
	if x != nil {
		return x.HashHeight
	}
	return nil
}

var File_common_types_protobuf_proto protoreflect.FileDescriptor

var file_common_types_protobuf_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x22, 0x28, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x1f,
	0x0a, 0x09, 0x48, 0x61, 0x73, 0x68, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x68,
	0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22,
	0x4f, 0x0a, 0x0f, 0x48, 0x61, 0x73, 0x68, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x24, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x22, 0x7b, 0x0a, 0x12, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2d, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x36, 0x0a, 0x0a, 0x68, 0x61, 0x73, 0x68, 0x48, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x52, 0x0a, 0x68, 0x61, 0x73, 0x68, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x42, 0x30, 0x5a,
	0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x65, 0x6e, 0x6f,
	0x6e, 0x2d, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x67, 0x6f, 0x2d, 0x7a, 0x65, 0x6e,
	0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_types_protobuf_proto_rawDescOnce sync.Once
	file_common_types_protobuf_proto_rawDescData = file_common_types_protobuf_proto_rawDesc
)

func file_common_types_protobuf_proto_rawDescGZIP() []byte {
	file_common_types_protobuf_proto_rawDescOnce.Do(func() {
		file_common_types_protobuf_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_types_protobuf_proto_rawDescData)
	})
	return file_common_types_protobuf_proto_rawDescData
}

var file_common_types_protobuf_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_common_types_protobuf_proto_goTypes = []interface{}{
	(*AddressProto)(nil),       // 0: types.AddressProto
	(*HashProto)(nil),          // 1: types.HashProto
	(*HashHeightProto)(nil),    // 2: types.HashHeightProto
	(*AccountHeaderProto)(nil), // 3: types.AccountHeaderProto
}
var file_common_types_protobuf_proto_depIdxs = []int32{
	1, // 0: types.HashHeightProto.hash:type_name -> types.HashProto
	0, // 1: types.AccountHeaderProto.address:type_name -> types.AddressProto
	2, // 2: types.AccountHeaderProto.hashHeight:type_name -> types.HashHeightProto
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_common_types_protobuf_proto_init() }
func file_common_types_protobuf_proto_init() {
	if File_common_types_protobuf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_types_protobuf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddressProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_types_protobuf_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HashProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_types_protobuf_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HashHeightProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_types_protobuf_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountHeaderProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_types_protobuf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_types_protobuf_proto_goTypes,
		DependencyIndexes: file_common_types_protobuf_proto_depIdxs,
		MessageInfos:      file_common_types_protobuf_proto_msgTypes,
	}.Build()
	File_common_types_protobuf_proto = out.File
	file_common_types_protobuf_proto_rawDesc = nil
	file_common_types_protobuf_proto_goTypes = nil
	file_common_types_protobuf_proto_depIdxs = nil
}
