// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/types/protobuf.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddressProto struct {
	Address              []byte   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddressProto) Reset()         { *m = AddressProto{} }
func (m *AddressProto) String() string { return proto.CompactTextString(m) }
func (*AddressProto) ProtoMessage()    {}
func (*AddressProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_283a3be7ca5abadb, []int{0}
}

func (m *AddressProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddressProto.Unmarshal(m, b)
}
func (m *AddressProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddressProto.Marshal(b, m, deterministic)
}
func (m *AddressProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressProto.Merge(m, src)
}
func (m *AddressProto) XXX_Size() int {
	return xxx_messageInfo_AddressProto.Size(m)
}
func (m *AddressProto) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressProto.DiscardUnknown(m)
}

var xxx_messageInfo_AddressProto proto.InternalMessageInfo

func (m *AddressProto) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

type HashProto struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashProto) Reset()         { *m = HashProto{} }
func (m *HashProto) String() string { return proto.CompactTextString(m) }
func (*HashProto) ProtoMessage()    {}
func (*HashProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_283a3be7ca5abadb, []int{1}
}

func (m *HashProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashProto.Unmarshal(m, b)
}
func (m *HashProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashProto.Marshal(b, m, deterministic)
}
func (m *HashProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashProto.Merge(m, src)
}
func (m *HashProto) XXX_Size() int {
	return xxx_messageInfo_HashProto.Size(m)
}
func (m *HashProto) XXX_DiscardUnknown() {
	xxx_messageInfo_HashProto.DiscardUnknown(m)
}

var xxx_messageInfo_HashProto proto.InternalMessageInfo

func (m *HashProto) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type HashHeightProto struct {
	Hash                 *HashProto `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Height               uint64     `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *HashHeightProto) Reset()         { *m = HashHeightProto{} }
func (m *HashHeightProto) String() string { return proto.CompactTextString(m) }
func (*HashHeightProto) ProtoMessage()    {}
func (*HashHeightProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_283a3be7ca5abadb, []int{2}
}

func (m *HashHeightProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashHeightProto.Unmarshal(m, b)
}
func (m *HashHeightProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashHeightProto.Marshal(b, m, deterministic)
}
func (m *HashHeightProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashHeightProto.Merge(m, src)
}
func (m *HashHeightProto) XXX_Size() int {
	return xxx_messageInfo_HashHeightProto.Size(m)
}
func (m *HashHeightProto) XXX_DiscardUnknown() {
	xxx_messageInfo_HashHeightProto.DiscardUnknown(m)
}

var xxx_messageInfo_HashHeightProto proto.InternalMessageInfo

func (m *HashHeightProto) GetHash() *HashProto {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *HashHeightProto) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type AccountHeaderProto struct {
	Address              *AddressProto    `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	HashHeight           *HashHeightProto `protobuf:"bytes,2,opt,name=hashHeight,proto3" json:"hashHeight,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AccountHeaderProto) Reset()         { *m = AccountHeaderProto{} }
func (m *AccountHeaderProto) String() string { return proto.CompactTextString(m) }
func (*AccountHeaderProto) ProtoMessage()    {}
func (*AccountHeaderProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_283a3be7ca5abadb, []int{3}
}

func (m *AccountHeaderProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountHeaderProto.Unmarshal(m, b)
}
func (m *AccountHeaderProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountHeaderProto.Marshal(b, m, deterministic)
}
func (m *AccountHeaderProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountHeaderProto.Merge(m, src)
}
func (m *AccountHeaderProto) XXX_Size() int {
	return xxx_messageInfo_AccountHeaderProto.Size(m)
}
func (m *AccountHeaderProto) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountHeaderProto.DiscardUnknown(m)
}

var xxx_messageInfo_AccountHeaderProto proto.InternalMessageInfo

func (m *AccountHeaderProto) GetAddress() *AddressProto {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *AccountHeaderProto) GetHashHeight() *HashHeightProto {
	if m != nil {
		return m.HashHeight
	}
	return nil
}

func init() {
	proto.RegisterType((*AddressProto)(nil), "types.AddressProto")
	proto.RegisterType((*HashProto)(nil), "types.HashProto")
	proto.RegisterType((*HashHeightProto)(nil), "types.HashHeightProto")
	proto.RegisterType((*AccountHeaderProto)(nil), "types.AccountHeaderProto")
}

func init() { proto.RegisterFile("common/types/protobuf.proto", fileDescriptor_283a3be7ca5abadb) }

var fileDescriptor_283a3be7ca5abadb = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4e, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x2f, 0xa9, 0x2c, 0x48, 0x2d, 0xd6, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x4f, 0x2a,
	0x4d, 0xd3, 0x03, 0x33, 0x84, 0x58, 0xc1, 0xa2, 0x4a, 0x1a, 0x5c, 0x3c, 0x8e, 0x29, 0x29, 0x45,
	0xa9, 0xc5, 0xc5, 0x01, 0x60, 0x61, 0x09, 0x2e, 0xf6, 0x44, 0x08, 0x5f, 0x82, 0x51, 0x81, 0x51,
	0x83, 0x27, 0x08, 0xc6, 0x55, 0x92, 0xe7, 0xe2, 0xf4, 0x48, 0x2c, 0xce, 0x80, 0x28, 0x13, 0xe2,
	0x62, 0xc9, 0x48, 0x2c, 0xce, 0x80, 0xaa, 0x01, 0xb3, 0x95, 0xfc, 0xb9, 0xf8, 0x41, 0x0a, 0x3c,
	0x52, 0x33, 0xd3, 0x33, 0x4a, 0x20, 0xca, 0x54, 0x90, 0x94, 0x71, 0x1b, 0x09, 0xe8, 0x81, 0xed,
	0xd4, 0x83, 0x1b, 0x03, 0xd1, 0x28, 0x24, 0xc6, 0xc5, 0x96, 0x01, 0xd6, 0x24, 0xc1, 0xa4, 0xc0,
	0xa8, 0xc1, 0x12, 0x04, 0xe5, 0x29, 0x55, 0x73, 0x09, 0x39, 0x26, 0x27, 0xe7, 0x97, 0xe6, 0x95,
	0x78, 0xa4, 0x26, 0xa6, 0xa4, 0x16, 0x41, 0xcc, 0xd4, 0x45, 0x75, 0x21, 0xb7, 0x91, 0x30, 0xd4,
	0x58, 0x64, 0x7f, 0xc0, 0x9d, 0x2d, 0x64, 0xc6, 0xc5, 0x95, 0x01, 0x77, 0x15, 0xd8, 0x02, 0x6e,
	0x23, 0x31, 0x24, 0x87, 0x20, 0x39, 0x37, 0x08, 0x49, 0x65, 0x12, 0x1b, 0x38, 0x98, 0x8c, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x97, 0x1a, 0x1e, 0x98, 0x45, 0x01, 0x00, 0x00,
}
